package cn.edm.web.action;

import org.springframework.beans.factory.annotation.Autowired;

import cn.edm.app.jms.NotifyMessageProducer;
import cn.edm.modules.cache.Ehcache;
import cn.edm.service.AdapterService;
import cn.edm.service.BrowserService;
import cn.edm.service.CampaignService;
import cn.edm.service.CategoryService;
import cn.edm.service.CndService;
import cn.edm.service.CopyService;
import cn.edm.service.CorpService;
import cn.edm.service.CosService;
import cn.edm.service.DomainService;
import cn.edm.service.EmailService;
import cn.edm.service.ExportService;
import cn.edm.service.FilterService;
import cn.edm.service.FormService;
import cn.edm.service.HistoryService;
import cn.edm.service.HourService;
import cn.edm.service.ImportService;
import cn.edm.service.IpService;
import cn.edm.service.LabelService;
import cn.edm.service.LangService;
import cn.edm.service.MenuService;
import cn.edm.service.OsService;
import cn.edm.service.PlanService;
import cn.edm.service.PropService;
import cn.edm.service.RecipientService;
import cn.edm.service.RegionService;
import cn.edm.service.ResourceService;
import cn.edm.service.ResultService;
import cn.edm.service.RobotService;
import cn.edm.service.RoleMenuService;
import cn.edm.service.RoleService;
import cn.edm.service.SelectionService;
import cn.edm.service.SenderService;
import cn.edm.service.SettingService;
import cn.edm.service.TagService;
import cn.edm.service.TaskService;
import cn.edm.service.TemplateService;
import cn.edm.service.TouchService;
import cn.edm.service.TrigerService;
import cn.edm.service.UrlService;
import cn.edm.service.UserDetailsServiceImpl;
import cn.edm.service.UserService;
import cn.edm.service.WriterService;
import cn.edm.service.sync.ExportSync;
import cn.edm.service.sync.ImportSync;

public class Action {

    @Autowired protected AdapterService adapterService;
    @Autowired protected BrowserService browserService;
    @Autowired protected CampaignService campaignService;
    @Autowired protected CategoryService categoryService;
    @Autowired protected CndService cndService;
    @Autowired protected CopyService copyService;
    @Autowired protected CorpService corpService;
    @Autowired protected CosService cosService;
    @Autowired protected DomainService domainService;
    @Autowired protected EmailService emailService;
    @Autowired protected ExportService exportService;
    @Autowired protected FilterService filterService;
    @Autowired protected FormService formService;
    @Autowired protected HistoryService historyService;
    @Autowired protected HourService hourService;
    @Autowired protected ImportService importService;
    @Autowired protected IpService ipService;
    @Autowired protected LabelService labelService;
    @Autowired protected LangService langService;
    @Autowired protected MenuService menuService;
    @Autowired protected OsService osService;
    @Autowired protected PlanService planService;
    @Autowired protected PropService propService;
    @Autowired protected RecipientService recipientService;
    @Autowired protected RegionService regionService;
    @Autowired protected ResourceService resourceService;
    @Autowired protected ResultService resultService;
    @Autowired protected RobotService robotService;
    @Autowired protected RoleMenuService roleMenuService;
    @Autowired protected RoleService roleService;
    @Autowired protected SelectionService selectionService;
    @Autowired protected SenderService senderService;
    @Autowired protected SettingService settingService;
    @Autowired protected TagService tagService;
    @Autowired protected TaskService taskService;
    @Autowired protected TemplateService templateService;
    @Autowired protected TouchService touchService;
    @Autowired protected TrigerService trigerService;
    @Autowired protected UrlService urlService;
    @Autowired protected UserDetailsServiceImpl userDetailsServiceImpl;
    @Autowired protected UserService userService;
    @Autowired protected WriterService writerService;

    @Autowired protected ExportSync exportSync;
    @Autowired protected ImportSync importSync;
    
    @Autowired protected Ehcache cache;
    protected NotifyMessageProducer producer;
}
